#!/usr/bin/env bash
# scripts/00_configure.sh
# Interactively builds the .env file. Reuses any existing values as defaults and
# lets the user skip the Telegram channel and LLM provider sections to configure
# them later from inside the container. The GitHub memory repo is required.
#
# Honours HERMES_NONINTERACTIVE=1: in that mode it does not prompt and only
# validates the .env that is already present (used by the remote installer, which
# collects values on the controlling machine and copies .env to the Pi).
set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
LOG_TAG="00_configure"
# shellcheck source=scripts/lib/common.sh
source "$REPO_DIR/scripts/lib/common.sh"

ENV_FILE="$REPO_DIR/.env"

# Carry-through values not prompted here but preserved across re-runs.
MEM_LIMIT="$(env_get "$ENV_FILE" HERMES_MEM_LIMIT)"
BROWSER_PORT="$(env_get "$ENV_FILE" BROWSER_SERVER_PORT)"
DASHBOARD="$(env_get "$ENV_FILE" HERMES_DASHBOARD)"

# Existing values become the defaults for each prompt.
TELEGRAM_BOT_TOKEN="$(env_get "$ENV_FILE" TELEGRAM_BOT_TOKEN)"
TELEGRAM_ALLOWED_USERS="$(env_get "$ENV_FILE" TELEGRAM_ALLOWED_USERS)"
GITHUB_MEMORY_REPO="$(env_get "$ENV_FILE" GITHUB_MEMORY_REPO)"
GITHUB_TOKEN="$(env_get "$ENV_FILE" GITHUB_TOKEN)"
ANTHROPIC_API_KEY="$(env_get "$ENV_FILE" ANTHROPIC_API_KEY)"
OPENROUTER_API_KEY="$(env_get "$ENV_FILE" OPENROUTER_API_KEY)"
OPENROUTER_MODEL="$(env_get "$ENV_FILE" OPENROUTER_MODEL)"
HERMES_VOICE_ENABLED="$(env_get "$ENV_FILE" HERMES_VOICE_ENABLED)"
HERMES_STT_PROVIDER="$(env_get "$ENV_FILE" HERMES_STT_PROVIDER)"
HERMES_STT_MODEL="$(env_get "$ENV_FILE" HERMES_STT_MODEL)"
HERMES_TTS_PROVIDER="$(env_get "$ENV_FILE" HERMES_TTS_PROVIDER)"
HERMES_TTS_VOICE="$(env_get "$ENV_FILE" HERMES_TTS_VOICE)"
GROQ_API_KEY="$(env_get "$ENV_FILE" GROQ_API_KEY)"
ELEVENLABS_API_KEY="$(env_get "$ENV_FILE" ELEVENLABS_API_KEY)"
VOICE_TOOLS_OPENAI_KEY="$(env_get "$ENV_FILE" VOICE_TOOLS_OPENAI_KEY)"

# ── Validators ────────────────────────────────────────────────
valid_repo_url() { [[ "$1" =~ ^https://github\.com/[^/]+/[^/]+/?$ ]]; }
valid_user_ids() { [[ "$1" =~ ^[0-9]+(,[0-9]+)*$ ]]; }

write_env() {
  # Write the file fresh so it stays tidy, then lock it down.
  umask 077
  {
    echo "# Generated by scripts/00_configure.sh — re-run ./install.sh to change."
    echo
    echo "# Telegram channel (leave empty to configure later inside the container)"
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
    echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}"
    echo
    echo "# GitHub memory repository (required)"
    echo "GITHUB_MEMORY_REPO=${GITHUB_MEMORY_REPO}"
    echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
    echo
    echo "# LLM providers (leave empty to configure later inside the container)"
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
    echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
    echo "OPENROUTER_MODEL=${OPENROUTER_MODEL}"
    echo
    echo "# Runtime tuning"
    echo "HERMES_MEM_LIMIT=${MEM_LIMIT}"
    echo "BROWSER_SERVER_PORT=${BROWSER_PORT}"
    echo "HERMES_DASHBOARD=${DASHBOARD}"
    echo
    echo "# Voice mode (STT=speech-to-text, TTS=text-to-speech)"
    echo "HERMES_VOICE_ENABLED=${HERMES_VOICE_ENABLED}"
    echo "HERMES_STT_PROVIDER=${HERMES_STT_PROVIDER}"
    echo "HERMES_STT_MODEL=${HERMES_STT_MODEL}"
    echo "HERMES_TTS_PROVIDER=${HERMES_TTS_PROVIDER}"
    echo "HERMES_TTS_VOICE=${HERMES_TTS_VOICE}"
    echo "# Cloud voice API keys (only needed when STT/TTS provider is not local/edge)"
    echo "GROQ_API_KEY=${GROQ_API_KEY}"
    echo "ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}"
    echo "VOICE_TOOLS_OPENAI_KEY=${VOICE_TOOLS_OPENAI_KEY}"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

# ── Non-interactive: validate existing .env and exit ──────────
if [[ "${HERMES_NONINTERACTIVE:-0}" == "1" ]]; then
  [[ -f "$ENV_FILE" ]] || error ".env not found and running non-interactively."
  if [[ -z "$GITHUB_MEMORY_REPO" || -z "$GITHUB_TOKEN" ]]; then
    error "GITHUB_MEMORY_REPO and GITHUB_TOKEN are required but missing in .env."
  fi
  if ! valid_repo_url "$GITHUB_MEMORY_REPO"; then
    error "GITHUB_MEMORY_REPO must look like https://github.com/owner/repo."
  fi
  info "Using existing .env (non-interactive)."
  exit 0
fi

echo
note "── Hermes configuration ─────────────────────────────────────"
note "Answer the prompts below. Press Enter to keep a shown default."
echo

# ── Channel (Telegram) — skippable ────────────────────────────
note "Step 1/4 · Telegram channel"
if prompt_yesno "Configure the Telegram channel now? (skip to set it up later)" "y"; then
  prompt_secret "Telegram bot token (from @BotFather)" TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
  while :; do
    prompt_value "Allowed Telegram user IDs (comma-separated, from @userinfobot)" \
      TELEGRAM_ALLOWED_USERS "$TELEGRAM_ALLOWED_USERS"
    if [[ -z "$TELEGRAM_ALLOWED_USERS" ]] || valid_user_ids "$TELEGRAM_ALLOWED_USERS"; then
      break
    fi
    warn "User IDs must be numbers separated by commas, e.g. 111111111,222222222."
  done
else
  info "Skipped Telegram setup. Configure it later from inside the container."
fi
echo

# ── GitHub memory repo — required ─────────────────────────────
note "Step 2/4 · GitHub memory repository (required)"
while :; do
  prompt_value "Memory repo URL (https://github.com/owner/repo)" \
    GITHUB_MEMORY_REPO "$GITHUB_MEMORY_REPO"
  if valid_repo_url "$GITHUB_MEMORY_REPO"; then
    break
  fi
  warn "Enter a URL like https://github.com/owner/repo."
done
while :; do
  prompt_secret "GitHub token (repo scope)" GITHUB_TOKEN "$GITHUB_TOKEN"
  [[ -n "$GITHUB_TOKEN" ]] && break
  warn "A GitHub token is required to push memory."
done
echo

# ── LLM provider — skippable ──────────────────────────────────
note "Step 3/4 · LLM provider"
if prompt_yesno "Configure an LLM provider now? (skip to set it up later)" "y"; then
  local_provider=""
  prompt_value "Provider [anthropic/openrouter/both]" local_provider "anthropic"
  case "$local_provider" in
    anthropic)
      prompt_secret "Anthropic API key" ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY" ;;
    openrouter)
      prompt_secret "OpenRouter API key" OPENROUTER_API_KEY "$OPENROUTER_API_KEY" ;;
    both)
      prompt_secret "Anthropic API key" ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
      prompt_secret "OpenRouter API key" OPENROUTER_API_KEY "$OPENROUTER_API_KEY" ;;
    *)
      warn "Unknown provider '$local_provider'. Skipping; configure later." ;;
  esac
else
  info "Skipped provider setup. Configure it later from inside the container."
fi
echo

# ── Voice mode — optional ─────────────────────────────────────
note "Step 4/4 · Voice mode"
_voice_default="y"
[[ "${HERMES_VOICE_ENABLED:-1}" == "0" ]] && _voice_default="n"
if prompt_yesno "Enable voice mode? (send voice notes to the bot and get voice replies)" "$_voice_default"; then
  HERMES_VOICE_ENABLED=1
  prompt_value "STT provider [local/groq/openai]" HERMES_STT_PROVIDER "${HERMES_STT_PROVIDER:-local}"
  case "${HERMES_STT_PROVIDER}" in
    groq)
      prompt_secret "Groq API key (for cloud Whisper transcription)" GROQ_API_KEY "$GROQ_API_KEY" ;;
    openai)
      prompt_secret "OpenAI API key (for cloud Whisper transcription)" VOICE_TOOLS_OPENAI_KEY "$VOICE_TOOLS_OPENAI_KEY" ;;
    *)
      info "Local Whisper — no API key needed. Model '${HERMES_STT_MODEL:-base}' downloads on the first voice note." ;;
  esac
  prompt_value "TTS provider [edge/elevenlabs/openai/piper]" HERMES_TTS_PROVIDER "${HERMES_TTS_PROVIDER:-edge}"
  case "${HERMES_TTS_PROVIDER}" in
    elevenlabs)
      prompt_secret "ElevenLabs API key" ELEVENLABS_API_KEY "$ELEVENLABS_API_KEY" ;;
    openai)
      prompt_secret "OpenAI API key (for TTS)" VOICE_TOOLS_OPENAI_KEY "$VOICE_TOOLS_OPENAI_KEY" ;;
    *)
      info "No API key needed for '${HERMES_TTS_PROVIDER:-edge}'." ;;
  esac
else
  HERMES_VOICE_ENABLED=0
  info "Voice mode disabled. Re-run ./install.sh to enable it later."
fi
echo

# Defaults for tuning values when starting from scratch.
OPENROUTER_MODEL="${OPENROUTER_MODEL:-poolside/laguna-m.1:free}"
BROWSER_PORT="${BROWSER_PORT:-5555}"
DASHBOARD="${DASHBOARD:-1}"
HERMES_VOICE_ENABLED="${HERMES_VOICE_ENABLED:-1}"
HERMES_STT_PROVIDER="${HERMES_STT_PROVIDER:-local}"
HERMES_STT_MODEL="${HERMES_STT_MODEL:-base}"
HERMES_TTS_PROVIDER="${HERMES_TTS_PROVIDER:-edge}"
HERMES_TTS_VOICE="${HERMES_TTS_VOICE:-en-US-AriaNeural}"
GROQ_API_KEY="${GROQ_API_KEY:-}"
ELEVENLABS_API_KEY="${ELEVENLABS_API_KEY:-}"
VOICE_TOOLS_OPENAI_KEY="${VOICE_TOOLS_OPENAI_KEY:-}"

write_env
info "✓ Wrote $ENV_FILE (permissions 600)."
